Repository muhammadmuzzammil1998/catsay, pull requests merged in 2019-04, with the labels that each got.

#14 Fix width
  .travis.yml
  README.md
  app.go
  app_test.go
Labels: contribution, enhancement, version 2.1

#15 Fix wrong versioning
  .travis.yml
  README.md
  app.go
  app_test.go
Labels: version 2.1

#16 Version 2.1
  .dist/build.sh
  .gitignore
  .travis.yml
  README.md
  app.go
  app_test.go
Labels: enhancement, source code, version 2.1
